# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# set workdir
WORKDIR /app

# install dependencies
RUN pip install --no-cache-dir fastmcp==0.1.0 requests==2.31.0 python-dotenv==1.0.0

# copy application code
COPY . .

# environment variable for Steam API key
ENV STEAM_API_KEY=""

# run MCP via stdio
CMD ["python", "server.py"]
