name: Smithery Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Smithery CLI
      run: npm install -g @smithery/cli
      
    - name: Deploy to Smithery
      env:
        SMITHERY_API_KEY: ${{ secrets.SMITHERY_API_KEY }}
      run: smithery deploy 